version: '3.9'
services:
  recipe-database:
    image: mongo
    ports:
      - '27017:27017'
  recipe-backend:
    build: backend/
    environment:
      - PORT=3001
      - DATABASE_URL= mongodb://host.docker.internal:27017/recipes
    ports:
      - '3001:3001'
    depends_on:
      - recipe-database
  recipe-frontend:
    build:
      context: .
      args:
        VITE_BACKEND_URL: http://recipe-backend:3001/api/v1
    ports:
      - '3000:80'
    depends_on:
      - recipe-backend
